;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "0.1.1")
(def tag "v0.1.1")
(def generated-at "2024-06-24T08:41:55Z")
